export enum OrderStatus {
    INITIALIZED = "INITIALIZED",
    CONFIRMED = "CONFIRMED",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED",
    CANCELLED = "CANCELLED"
}