server:
  port: 8083
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eKirana_db
  application:
    name: ekirana-product-service
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    fetchRegistry: true
#    registerWithEureka: true
#  instance:
#    hostname: localhost
