server:
  port: 8085
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eKirana_db
  application:
    name: ekirana-image-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    fetchRegistry: true
#    registerWithEureka: true
#  instance:
#    hostname: localhost
